invenia/NamedDims.jl

- src/name_core.jl
It is a rule of generated functions that they can only call things defined before their own definition.
So depending on the order of function calls without this change world-age `MethodError`s can be thrown.
> move keep_dims_ind helper functions to be defined before generated function

- Project.toml
- src/name_core.jl
- src/wrapper_array.jl
- test/broadcasting.jl
- test/name_core.jl
- test/wrapper_array.jl
I am not happy with this.
It introduces another (particularly evil) `@generated` function,
and two `@pure` functions that are not really pure. But that are probably acceptable because if the generic function methods that they call get overwritten, then a bunch of things will break everywhere in the standard library.
It does however solve #8 
and it continues to run everything to do with names at compile time.
> Allow multiple wildcard names

- Project.toml
- src/functions.jl
- src/functions_math.jl
- test/functions_math.jl
- closes #41 
- NamedDims still only supports single-arg `cor`/`cov` i.e. for single input `X::AbstractMatrix` (or `x::AbstractVector`, which we get for free)
> Correct names for single input cov/cor

- Project.toml
- README.md
- src/NamedDims.jl
- src/wrapper_array.jl
- test/wrapper_array.jl
- closes #39
- `unname` allow you to ensure you _don't_ have a NamedDimsArray
> Add function for safely accessing `parent`

- Project.toml
- I forgot that pre v1.0 we can add functionality in patch releases
- #55 bumped the minor version -- this changes that so only the patch version is incremented
- now folks don't have to update compat to get the tiny backward-compatible feature
> Change to only increment the patch version

- src/NamedDims.jl
- No reliable way to identify the version
- More useful to assume a compatible Tracker
- see https://github.com/invenia/NamedDims.jl/pull/54#discussion_r297233900 (Thanks @KristofferC for noticing this)
> Stop making Tracker loading depend on version

- Project.toml
- src/functions.jl
- test/functions.jl
- Partial fix for #34 (1.0 support not added, separate issue now opened for that https://github.com/invenia/NamedDims.jl/issues/59)
- This allocates once more than expected (or maybe twice more, depending on your expectations)
- Joint work with @oxinabox who figured out how to reduce allocations at least this far
> Add `eachslice` for Julia 1.1+

- Project.toml
- src/functions_dims.jl
- test/functions_dims.jl
Minimal fix of a bug that crept in.
Maximal fix is this:
```
@eval function $f(nda::NamedDimsArray{L}) where (L)
data = $f(parent(nda))
new_names = if ndims(nda) == 1 # vector input
(:_, first(L))
elseif ndims(data) == 1 # vector output
(last(L),)
else
(last(L), first(L))
end
return NamedDimsArray(data, new_names)
end
```
> names(permutedims(transpose(ndv)))

- .travis.yml
- src/name_core.jl
- test/functions_math.jl
- test/name_core.jl
- test/wrapper_array.jl
This copies all the `@btime` comments in source to be real tests. 
Motivated by noticing that the one for `order_named_inds` fails on Julia 1.2, which leads to slow indexing:
```
data = rand(2,3);
nda = NamedDimsArray(data, (:row, :col))
@btime $data[2,3]
@btime $nda[2,3]  # good, 1 ns
@btime $nda[row=2, col=3] # bad, 200 ns (or 50 ns on 1.1)
```
I have a partial fix (50ns, but still nonzero allocations) which I'll add if you don't object, just two lines.
> Allocation tests from comments

- src/functions_dims.jl
- test/functions_dims.jl
This is a tiny fix of `reshape` to do what I think you intended, and avoid this:
```
nda = NamedDimsArray(rand(2, 3), (:r, :c))
reshape(nda, 1, :) # 1×6 reshape(::NamedDimsArray{(:r, :c), …
```
> reshape simple case

- Project.toml
- src/NamedDims.jl
- src/broadcasting.jl
- src/functions.jl
- src/functions_dims.jl
- src/functions_math.jl
- src/wrapper_array.jl
- test/broadcasting.jl
- test/functions.jl
- test/functions_dims.jl
- test/functions_math.jl
- test/tracker_compat.jl
- test/wrapper_array.jl
> Switched out `names` for `dimnames`

- src/NamedDims.jl
- src/name_core.jl
- src/wrapper_array.jl
- test/name_core.jl
- test/wrapper_array.jl
This solves the `order_named_inds` problem by just making it generated, I fiddled around but couldn’t make other ways work. Not sure whether the body should then live in src/name_core.jl (as now) or move to src/wrapper_array.jl (where the function of this signature used to live).
Before:
```
julia> nda = NamedDimsArray(rand(2,2), (:x, :y));
julia> @btime $nda[1, 2];
1.421 ns (0 allocations: 0 bytes)
julia> @btime $nda[x=1, y=2];
40.455 ns (2 allocations: 64 bytes)
```
After:
```
julia> @btime $nda[x=1, y=2]
1.420 ns (0 allocations: 0 bytes)
```
Edit: Note that this was the original motivation for #76. Which included a partial fix to get this down from 200ns.
> Make keyword indexing fast

- Project.toml
- README.md
- src/NamedDims.jl
- src/broadcasting.jl
- src/deprecations.jl
- src/wrapper_array.jl
- test/deprecations.jl
- test/runtests.jl
- test/wrapper_array.jl
This has never sat right with me.
That calling `NamedDimsArray` on a `NamedDimsArray` was the way to coerce wildcard names to have a particular name."
[PyTorch calls this operation `refine_names`](https://pytorch.org/docs/stable/named_tensor.html#torch.Tensor.refine_names)
i think this is a much better name for the function
> Replace name asserting constructor with refine names

- README.md
- src/NamedDims.jl
- src/functions_dims.jl
- src/name_operations.jl
- src/wrapper_array.jl
- test/functions_dims.jl
- test/name_operations.jl
- test/runtests.jl
- test/wrapper_array.jl
We have a few of them and they were crowding the already overlong `wrapper_array.jl` file,
except 1 which was in a totally different file with a bunch of overloaded functions
> reorganize functions that are only for NamedDimsArrays into their own file

- Project.toml
- src/functions.jl
- src/wrapper_array.jl
- test/wrapper_array.jl
Because right now StridedArray is a  Union and thus not extensible
(see https://github.com/JuliaLang/julia/pull/30432)
you don't need to implement `strides` explictly for all new strided array types,
which we can assume (and then be proven wrong with later method errors) 
that our wrapped type is.
This is needed for some BLAS stuff called by Distributions.jl
> Add Strided Array Interface

- Project.toml
- src/name_operations.jl
- test/name_operations.jl
If `dimnames` is the official way to extract names, then perhaps `dimnames(A, d)` ought to work like `size(A, d)`.
> dimnames(A, d)

- test/name_operations.jl
- test/runtests.jl
- test/wrapper_array.jl
Relates to tests in #115 .
The `using SparseArrays` makes sure the tests in `name_operations.jl` can run standalone. Sorry for including it here, added this commit earlier and it slipped in here.
> Mark allocation tests broken in julia 1.4

- Project.toml
- src/functions_math.jl
- test/functions_math.jl
Adds tests and the two methods which resolve the ambiguities. Closes #112 and #60.
> Resolve method ambiguity on Adjoint and Diagonal

- test/functions.jl
In [julia 1.5](https://docs.julialang.org/en/v1/NEWS/) count accepts dims argument, which fails two tests in `test/functions.jl`.
https://github.com/invenia/NamedDims.jl/blob/32d8f693b6ed8e1d1eec9104b0e9d3f61de896af/test/functions.jl#L170-L171
At present the behaviour is:
```
julia> a = [true false; true true];
julia> nda = NamedDimsArray(a, (:x, :y));
julia> count(nda, dims=:x)
1×2 NamedDimsArray{(:x, :y),Int64,2,Array{Int64,2}}:
2  1
```
It seems reasonable to me that an NDA is returned, rather than an array. Do people have different opinions?
> fix tests for count with dims argument for julia 1.5

- Project.toml
- src/functions_math.jl
- test/functions_math.jl
Fixes small bug affecting NDAs constructed from CoVectors:
```
julia> v = [1, 2, 3];
julia> ndv = NamedDimsArray{(:vec, )}(v)
3-element NamedDimsArray{(:vec,),Int64,1,Array{Int64,1}}:
1
2
3
```
before the fix:
```
julia> NamedDimsArray{(:_, :_)}(v') * ndv
ERROR: DimensionMismatch("Cannot take matrix product of arrays with different inner dimension names. _ vs vec")
Stacktrace:
[1] throw_matrix_dim_error(::Symbol, ::Symbol) at /Users/mzgubic/.julia/dev/NamedDims.jl/src/functions_math.jl:18
[2] *(::NamedDimsArray{(:_, :_),Int64,2,Adjoint{Int64,Array{Int64,1}}}, ::NamedDimsArray{(:vec,),Int64,1,Array{Int64,1}}) at /Users/mzgubic/.julia/dev/NamedDims.jl/src/functions_math.jl:38
[3] top-level scope at REPL[75]:1
```
after the fix:
```
julia> NamedDimsArray{dimnames(v')}(v') * ndv
14
```
> Fix a bug affecting NDAs constructed from CoVectors

- Project.toml
- src/functions_math.jl
- src/name_core.jl
- test/name_core.jl
- test/runtests.jl
- test/test_helpers.jl
Closes #112
Makes #128 redundant
Cause is:
https://github.com/JuliaLang/julia/pull/36679
removed a defintiion of matmul with `Adjoint{<:Any}` and replaced it with one with `Adjoint{<:Number}`
we were winning that ambiguity fight before, but now it ties.
This PR changes us to match.
> fix ambiguity on julia 1.5

- .travis.yml
This one got missed when we were setting up all the nightly jobs.
That, combined with not having the CI set to run on latest stable (fixed in #114) is why #115  went unnoticed.
> Connect to RSE-Nightly

- .appveyor.yml
Tests are actually failing on 1.1 right now, we only really are interested in supporting  testing LTS and Stable.
The failures are pretty meaningless
> Only test LTS and stable

- Project.toml
- src/cat.jl
- src/name_core.jl
- src/wrapper_array.jl
- test/cat.jl
I was chasing ambiguities, and found the following bugs in the handling of `hcat` here: 
```julia
julia> using NamedDims
julia> nda = NamedDimsArray(rand(2,3), (:x, :y));
julia> ndv = NamedDimsArray(rand(2), (:x,));
julia> hcat(nda, ndv) # has lost a name
2×4 NamedDimsArray{(:x, :_), Float64, 2, Matrix{Float64}}:
0.434524    0.73716   0.509066  0.309907
0.00329738  0.669837  0.154734  0.405725
julia> hcat(nda, nda.data') # wrong sizes, but no error
2×6 NamedDimsArray{(:x, :y), Float64, 2, Matrix{Float64}}:
0.434524    0.73716   0.509066  0.434524    0.73716   0.509066
0.00329738  0.669837  0.154734  0.00329738  0.669837  0.154734
```
So I tried to fix them. Existing tests are untouched, and all pass. On the new testset, NamedDims v0.2.26 gives 2 passed, 4 failed, 3 errored, 0 broken.
I …
> `hcat` tricky cases

- src/NamedDims.jl
- src/broadcasting.jl
- src/cat.jl
- src/functions.jl
- src/functions_dims.jl
- src/functions_math.jl
- src/name_core.jl
- src/name_operations.jl
- src/tracker_compat.jl
- src/wrapper_array.jl
Same as #137 but with `whitespace_typedefs=false` (i.e. Run JuliaFormatter as a way to test out domluna/JuliaFormatter.jl#295)
```julia
julia> format(
"src/"; 
style=BlueStyle(),  # requires JuliaFormatter v0.8.2 https://github.com/domluna/JuliaFormatter.jl.git#bluestyle-1
always_use_return=true,
short_to_long_function_def=true,
whitespace_ops_in_indices=true,
remove_extra_newlines=true,
always_for_in=true,
import_to_using=true,
pipe_to_function_call=true,
whitespace_in_kwargs=false,
whitespace_typedefs=false,
)
```
(fyi it's also possible to tell some bits to not be formatted https://domluna.github.io/JuliaFormatter.jl/stable/skipping_formatting/)
> Run formatter (without typedef whitespace)

- Project.toml
- src/name_operations.jl
- src/wrapper_array.jl
- test/name_operations.jl
- test/wrapper_array.jl
This allows `numerical_dims = dim(A, dims)` to work for any array, by doing nothing when `A` doesn't have names. This closes #136.
It also allows `unname(A)` to accept anything, so that `map(unname, args)` can strip all dimension names without first checking which arguments are are arrays.
> make unname accept anything, and dim accept AbstractArray + number (Close #136)

- Project.toml
- src/cat.jl
- test/cat.jl
```
julia> vcat(1:3, NamedDimsArray(4:6, :x))
ERROR: MethodError: vcat(::UnitRange{Int64}, ::NamedDimsArray{(:x,), Int64, 1, UnitRange{Int64}}) is ambiguous. Candidates:
vcat(V::AbstractVector{T}...) where T in Base at abstractarray.jl:1477
vcat(V::AbstractVector{T} where T...) in Base at abstractarray.jl:1476
vcat(a::AbstractVecOrMat{T} where T, b::Union{NamedDimsArray{L, T, 1, A} where A<:AbstractVector{T}, NamedDimsArray{L, T, 2, A} where A<:AbstractMatrix{T}} where T where L, cs::AbstractVecOrMat{T} where T...) in NamedDims at /Users/me/.julia/packages/NamedDims/ty09T/src/cat.jl:37
Possible fix, define
vcat(::AbstractVector{T}, ::NamedDimsArray{L, T, 1, A} where A<:AbstractVector{T} where L, ::Vararg{AbstractVector{T}, N} where N) where T
```
So I did.
> Fix a `vcat` ambiguity

- .github/workflows/CI.yml
This will unblock #167 
Pkg for 1.0 doesn't do tiered  resolution.
I.e. it can't do the thing where it downgrades main dependency in order to install test dependencies
We do want to keep supporting 1.0 in principle, but it's not really viable to test through CI. 😞
> stop testing on 1.0

- Project.toml
- src/wrapper_array.jl
- test/wrapper_array.jl
When using an `OffsetArray` for the parent array inside of a `NamedDimsArray`, calling `similar` converts the parent array to a regular dense `Array`
```
using NamedDims
using OffsetArrays
oa = OffsetArray([1,2,3], -1:1)
nda = NamedDimsArray(oa, (:x,))
parent(similar(nda)) isa OffsetArray # false
parent(similar(nda)) isa Array # true
```
This is fixed by changing `size(A)` into `axes(A)` within `named_size`. `named_size` is called to determine the length of every dimension and attach this length to its corresponding dimension name. However, when we use an `OffsetArray`, the length is not sufficient to reconstruct the array as we also need the offset. When just lengths are supplied, `OffsetArray` falls back to default `Array`s, leading to the bug.
> Use `axes` instead of `size` within `similar`

- Project.toml
- src/name_core.jl
This should remove this warning:
```
┌ Warning: use values(kwargs) and keys(kwargs) instead of kwargs.data and kwargs.itr
│   caller = #order_named_inds#17 at name_core.jl:179 [inlined]
└ @ Core ~/.julia/packages/NamedDims/TpffL/src/name_core.jl:179
```
> Avoid `kw.data`

- Project.toml
- src/broadcasting.jl
- test/broadcasting.jl
Closes #175.
Wow, this took me a while (hard to debug base functions), and I still don't understand how broadcasting works. The issue was that when the inner broadcasting style was extracted, the axes were not updated to the axes that `instantiate` returns for the outer style.
> Fix broadcasting bug

- Project.toml
- src/broadcasting.jl
- test/broadcasting.jl
Apparently less recursion helps the compiler to const-propagate.
Fixes #187.
> 2-argument function to help const propagation in broadcasted_names()

- .github/workflows/CI.yml
- Project.toml
- src/functions_linearalgebra.jl
- test/functions_linearalgebra.jl
Presently `Cholesky` isn't supported with `NamedDims`. 
Adding this was made fairly easy with the `NamedFactorisation`. It throws a dimensionamismatch if the axes are not named the same. Also includes the suggested linting changes from JuliaFormatter for some lines that were not part of this MR.
> Add Cholesky factorisation

- Project.toml
- src/chainrules.jl
- test/chainrules.jl
- test/runtests.jl
> implement `ProjectTo` for `NamedDimsArray`

- Project.toml
Since the 0.3 was non-breaking https://github.com/invenia/NamedDims.jl/pull/202#discussion_r937572855
we can probably do this and avoid changing all the compats everywhere
> Release HEAD as 0.2 since 0.3 was nonbreaking

- Project.toml
This is pretty much stable.
This release will be nonbreaking and the same as the last 0.3.x release which is frustrating but still better I think than leaving this 0.x forever.
Though maybe this isn't as stable as i thought, why did we release 0.3?
Invenia's new  internal policy is to create packages at 1.0.0 and never use  0.x.y versioning
> Release 1.0 ?

- Project.toml
- src/cat.jl
- test/cat.jl
`_named_*cat` funcs rely on constant propagation of names, so they need inlining to infer
> infer reduce(*cat)
