invenia/NamedDims.jl

Project.toml, README.md, src/NamedDims.jl, src/functions_dims.jl, src/functions_math.jl, src/name_core.jl, src/wrapper_array.jl, test/functions_dims.jl, test/functions_math.jl, test/name_core.jl, test/runtests.jl, test/wrapper_array.jl
This does array math.
Closes #3 
The + and - will likely need to be redone after #4 
since at least `Base` just defined them to call the Broadcasting equiv.
But they are the simple part of this PR, the  complexity is in `*`
=> basic math

src/NamedDims.jl, src/broadcasting.jl, src/functions_math.jl, src/name_core.jl, src/wrapper_array.jl, test/broadcasting.jl, test/functions_dims.jl, test/functions_math.jl, test/name_core.jl, test/runtests.jl, test/wrapper_array.jl
This is the PR for broadcasting.
I am currently pointing it it #7 
just so the differences can be seen easily.
And so can parallelize reviewing
After #7 is merged I will rebase this and re-open this PR against master
=> Add Broadcasting

src/name_core.jl, test/name_core.jl
=> throw error if a non-matching dimension name is passed in 

src/compat.jl, src/functions_math.jl, test/functions_math.jl
=> More matmuls, more easily

README.md
Currently there are no docs worth linking to and the deploy key is not setup
=> comment out docs link

Project.toml, src/functions.jl, test/functions.jl
=> Correct default dims keywords to match Base

src/NamedDims.jl, src/functions_dims.jl, src/functions_math.jl, test/functions_math.jl
=> Fix vector' * vector

test/functions.jl, test/functions_dims.jl
- As noticed in review, #48 added more testsets and with the added indentation some test are now egregiously beyond the usual 88 char line length... which makes working on my laptop more difficult 😆  
- This PR simply changes the style in tests a little, we limit the width at the cost of more vertical space -- seems okay to me
=> Split long tests over multiple lines

Project.toml, src/functions.jl, src/wrapper_array.jl, test/functions.jl, test/wrapper_array.jl
This should make `push!` and friends work.
=> Mutating functions

src/functions.jl, src/name_core.jl, test/functions.jl, test/name_core.jl
These give an error if names don’t match. I guess the other option would be to permute things to make it work if possible.
=> sum!, prod! etc

Project.toml, src/broadcasting.jl, test/broadcasting.jl
=> copyto! for broadcasting

Project.toml, src/functions.jl, src/name_core.jl, test/functions.jl, test/name_core.jl
Closes #75.
Edit: test failure is an ambiguity on 1.0.
=> map + collect

Project.toml, src/functions.jl, src/name_core.jl, test/functions.jl, test/name_core.jl
This declares that arrays with incompatible names are not equal.
=> isequal and ==

README.md
=> Add `dim` to README

Project.toml, src/name_core.jl, src/wrapper_array.jl, test/functions_math.jl, test/name_core.jl, test/runtests.jl, test/wrapper_array.jl
=> Use ballocated for tests

Project.toml, src/functions.jl, test/functions.jl
This is a minimal change to add `sortslices`.
=> Add sortslices

src/functions_dims.jl
This implements the "maximal fix" suggested in https://github.com/invenia/NamedDims.jl/pull/77, which reads the dimension actually created by `transpose(data)` rather than predicting this from the type `Transpose{T,<:Vector}` etc. 
The reason to do this is that, if another wrapper behaves like `NamedDimsArray` does, and wraps such a `Transpose`, then it can't at present live inside this one. In particular, I want this for commutative wrappers here:
https://github.com/mcabbott/AxisKeys.jl/blob/3a3907afd475098e499188715809f5f2a2c28b8c/test/_functions.jl#L35
=> Simpler handling of transpose(transpose()) etc.

Project.toml, src/name_core.jl, src/wrapper_array.jl, test/name_core.jl, test/wrapper_array.jl
=> Indexing by BitArray{3}, etc.

Project.toml, src/wrapper_array.jl, test/wrapper_array.jl
=> Fix the getindex/setindex bug referenced in #110

Project.toml, src/name_core.jl, src/name_operations.jl, test/name_operations.jl
=> rename with arbitrary number of pairs

Project.toml, src/broadcasting.jl, test/broadcasting.jl
Closes #140 
Figures it was worth at this point refacting out to an `@eval` loop
=> Fix broadcasting against tuples

src/functions_linearalgebra.jl, test/functions_linearalgebra.jl
- Reduce required code by making a `NamedFactorization` type
=> Add linalg factorizations

README.md
Document the exported function `dimnames`
=> Document `dimnames`

src/name_core.jl, test/name_core.jl, test/wrapper_array.jl
=> Drop names with a vector of linear indices

test/test_helpers.jl
Closes #152
Version is already bumped, so this needs to be merged & tagged.
=> Fix tests on 1.6

Project.toml, src/functions_linearalgebra.jl, test/functions_linearalgebra.jl
=> Fix factorizations that don't have same eltype as input

Project.toml
Edit: closes #167 
I completely forgot about that. But the test issue which blocked it has been fixed.
=> Allow AbstractFFTs.jl v1

Project.toml, src/NamedDims.jl, src/functions_math.jl, test/functions_math.jl
Rebases #122, closes #120.
Needed to get performance improvements in the CovarianceEstimation (in one of our internal packages)
=> Extend CovarianceEstimation.cov

.gitignore, Project.toml, src/NamedDims.jl, src/chainrules.jl, test/chainrules.jl, test/runtests.jl
=> Add `rrule`s for constructors

Project.toml, test/functions_linearalgebra.jl
=> use ColumnNorm() and NoPivot() instead of Val(true) and Val(false) in qr calls

src/functions.jl, test/functions.jl
=> add {arg/find}{min/max} functions

Project.toml, src/functions_linearalgebra.jl, test/functions_linearalgebra.jl
=> implement `eigX` and `Xdet`
